import 'storybook-addon-vue-info/lib/register'
import '@storybook/addon-notes/register'
import '@storybook/addon-storysource/register'
import '@storybook/addon-viewport/register'
import '@storybook/addon-actions/register'
