const fs = require('fs')
const path = require('path')

const currentDir = path.dirname(__dirname)
const stylesPath = path.resolve('../../../_alpaca.scss')

if (
  currentDir.includes('node_modules') &&
  !fs.existsSync(stylesPath)
) {
  fs.writeFileSync(
    stylesPath,
    `// It's autogenerated file, here you can overwrite Alpaca's variables`
  )
}
