const fs = require('fs')
const path = require('path')

const stylesPath = path.resolve('./_alpaca.scss')

if (!fs.existsSync(stylesPath)) {
  fs.writeFileSync(stylesPath, `// It's autogenerated file, here you can overwrite Alpaca's variables`)
}
